/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ReverseRequestService } from "../reverseRequest.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ReverseRequestCreateInput } from "./ReverseRequestCreateInput";
import { ReverseRequest } from "./ReverseRequest";
import { ReverseRequestFindManyArgs } from "./ReverseRequestFindManyArgs";
import { ReverseRequestWhereUniqueInput } from "./ReverseRequestWhereUniqueInput";
import { ReverseRequestUpdateInput } from "./ReverseRequestUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ReverseRequestControllerBase {
  constructor(
    protected readonly service: ReverseRequestService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ReverseRequest })
  @nestAccessControl.UseRoles({
    resource: "ReverseRequest",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createReverseRequest(
    @common.Body() data: ReverseRequestCreateInput
  ): Promise<ReverseRequest> {
    return await this.service.createReverseRequest({
      data: {
        ...data,

        transaction: data.transaction
          ? {
              connect: data.transaction,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        reason: true,
        requestDate: true,
        status: true,

        transaction: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ReverseRequest] })
  @ApiNestedQuery(ReverseRequestFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ReverseRequest",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async reverseRequests(
    @common.Req() request: Request
  ): Promise<ReverseRequest[]> {
    const args = plainToClass(ReverseRequestFindManyArgs, request.query);
    return this.service.reverseRequests({
      ...args,
      select: {
        createdAt: true,
        id: true,
        reason: true,
        requestDate: true,
        status: true,

        transaction: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ReverseRequest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ReverseRequest",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async reverseRequest(
    @common.Param() params: ReverseRequestWhereUniqueInput
  ): Promise<ReverseRequest | null> {
    const result = await this.service.reverseRequest({
      where: params,
      select: {
        createdAt: true,
        id: true,
        reason: true,
        requestDate: true,
        status: true,

        transaction: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ReverseRequest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ReverseRequest",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateReverseRequest(
    @common.Param() params: ReverseRequestWhereUniqueInput,
    @common.Body() data: ReverseRequestUpdateInput
  ): Promise<ReverseRequest | null> {
    try {
      return await this.service.updateReverseRequest({
        where: params,
        data: {
          ...data,

          transaction: data.transaction
            ? {
                connect: data.transaction,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          reason: true,
          requestDate: true,
          status: true,

          transaction: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ReverseRequest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ReverseRequest",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteReverseRequest(
    @common.Param() params: ReverseRequestWhereUniqueInput
  ): Promise<ReverseRequest | null> {
    try {
      return await this.service.deleteReverseRequest({
        where: params,
        select: {
          createdAt: true,
          id: true,
          reason: true,
          requestDate: true,
          status: true,

          transaction: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
